### ISSUE TITLE
No compila index.html

### ISSUE THREAD

**Issue by surielmx** [platzi/platzifrontend-marvel#7]
Localmente, antes del video de gulp, ya no me muestra ninguna página, marca error en /signin, que no encuentra dicha página. Clone este repo y marca el mismo error. Lo que me di cuenta es que no compila el index.jade a index.html. Desde que se agrego jadeify ya no se genera el index.html. En el video no se por que si le funciona, pero en este repo no

**Comment by LeonidasEsteban** [comment]
Seguro no compilaste jade antes de correr el servidor, agregué una tarea para que lo hagas en este commit https://github.com/platzi/platzifrontend-marvel/commit/169b5b3fa47ca556f5a844e7f4f799ca0f8bc3ec

**Comment by surielmx** [comment]
Este guido ya elmina esta linea, por que dice que ya no la necesitamos, pues ya agregamos jadeify:
"jade": "jade --watch --pretty lib/*.jade --out 

ok, deja lo reviso, gracias

**Comment by LeonidasEsteban** [comment]
Tal como está esa no sirve, pero lo que te puse sip solo haz pull y corre npm run jade ^ ^
