### ISSUE TITLE
Optimización peticiones Marvel

### ISSUE THREAD

**Issue by landinezrichard** [platzi/platzifrontend-marvel#8]
Buen día, en la segunda promesa, en el archivo "/lib/avengers.js" se está haciendo una promesa (o petición) por cada uno de los 20 personajes, esto se puede optimizar de una forma muy fácil, en los resultados de la primera petición, en el campo "characters" nos indica:

"characters": {
          "available": 105,
          "collectionURI": "http://gateway.marvel.com/v1/public/series/354/characters",

Esto indica que hay 105 personajes disponibles, y la url a la que le podemos hacer esa petición (en vez de hacer la petición a la url de cada personaje), solo hay que hacer una segunda promesa a esa url, en la cual, si queremos con el parámetro "limit" podemos pedir, por ejemplo 40 personajes:

http://gateway.marvel.com:80/v1/public/series/354/characters?limit=40&apikey=........

También, para que se demore menos en cargar las imágenes, podemos indicarle un tamaño para el thumbnail, esto se hace en el mismo archivo, cuando cambiamos las imagenes de cada "Card" por ejemplo:

const imageSize = "standard_amazing";

```
$image.attr('src', `${character.thumbnail.path}/${imageSize}.${character.thumbnail.extension}`);
```

Espero les sirvan estas optimizaciones, Saludos.

**Comment by jeduan** [comment]
Si! Definitivamente si fuera código de producción seria algo a tomar en cuenta.

En un video posterior creo un cache de los personajes en localStorage y de esta forma solo tenemos que pedir datos la primera vez que carga la aplicación, que se me hizo otra forma interesante de presentar la idea que siempre hay mas de una ruta para optimizar el código.
